#
# Copyright The Titan Project Contributors.
#

#
# We use release drafter to keep the in-progress release notes up to date:
#
#   https://github.com/marketplace/actions/release-drafter
#
name: Draft Release

on:
  push:
    branches:
      - master

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: toolmantim/release-drafter@v5.5.0
        id: draft_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: echo
        run: echo $UPLOAD_URL
        env:
          UPLOAD_URL: ${{ steps.draft_release.outputs.upload_url }}
